apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - vishalvyas.com
    - imvishalvyas.com
    secretName: letsencrypt-prod
  rules:
  - host: vishalvyas.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
  - host: imvishalvyas.com
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 80
